---
services:
  db:
    image: postgres:17-alpine
    container_name: weather-services-api-db
    ports:
      - "5555:5432"
    volumes:
      - .:/weather-services-api-db
      - data:/var/lib/postgresql/data
    shm_size: 192m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather

volumes:
  data:
